#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

import argparse
import os
import sys

from mbtilesd.app import app, load_config


def parse_args(args):
    """Parses command-line `args`"""

    parser = argparse.ArgumentParser(
        description='Serves MBTiles files'
    )
    parser.add_argument('--debug',
                        action='store_const', const=True, default=False,
                        help='Debug mode')
    parser.add_argument('--config',
                        default=None,
                        help='Override default configuration.')

    group = parser.add_argument_group(title='Positional arguments')
    group.add_argument('paths', metavar='DIR', nargs='*',
                       help='Search path for MBTiles files')

    group = parser.add_argument_group(title='Networking arguments')
    group.add_argument('--host',
                       default='127.0.0.1',
                       help=('IP to listen to. Set to 0.0.0.0 to listen'
                             'on all interfaces. Defaults to 127.0.0.1'))
    group.add_argument('--port',
                       default=5000, type=int,
                       help='Port to listen on. Defaults to 5000')
    group.add_argument('--server', dest='servers',
                       action='append', default=[],
                       help='Servers that host tile images')

    args = parser.parse_args(args=args)

    load_config(filename=args.config)
    if args.debug:
        app.config['DEBUG'] = args.debug
    if args.paths:
        app.config['PATHS'] = args.paths
    if args.servers:
        app.config['SERVERS'] = args.servers

    return args


def main(args):
    args = parse_args(args=args)
    app.run(host=args.host,
            port=args.port)
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
