#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

import argparse
import sys

from mbtilesd.app import app


def parse_args(args):
    """Parses command-line `args`"""

    parser = argparse.ArgumentParser(
        description='Serves MBTiles files'
    )
    parser.add_argument('--debug',
                        action='store_const', const=True, default=False,
                        help='Debug mode')

    group = parser.add_argument_group(title='Positional arguments')
    group.add_argument('paths', metavar='DIR', nargs='+',
                       help='Search path for MBTiles files')

    group = parser.add_argument_group(title='Networking arguments')
    group.add_argument('--host',
                       default='127.0.0.1',
                       help=('IP to listen to. Set to 0.0.0.0 to listen'
                             'on all interfaces. Defaults to 127.0.0.1'))
    group.add_argument('--port',
                       default=5000, type=int,
                       help='Port to listen on. Defaults to 5000')
    group.add_argument('--server', dest='servers',
                       action='append', default=None,
                       help='Servers that host tile images')

    return parser.parse_args(args=args)


def main(args):
    args = parse_args(args=args)
    app.config.update(dict(
        paths=args.paths,
        servers=args.servers
    ))
    app.run(host=args.host,
            port=args.port,
            debug=args.debug)
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
